services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - 'data_es:/usr/share/postgresql/data/pgdata'
    networks:
      - postgres

volumes:
  data_es:
    driver: local

networks:
  postgres: null